name: BPCA_CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: BPCalculator
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: BPCalculator
      
    - name: Run unit tests
      run: dotnet test BloodPressureUnitTests/BloodPressureUnitTests.csproj --verbosity normal
      
    - name: Run Specflow tests
      run: dotnet test SpecFlowBloodPressureTests/SpecFlowBloodPressureTests.csproj --verbosity normal
    
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: BPCalculator
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: BPCalculator
      
    - name: Sonarscanner for dotnet
      uses: Secbyte/dotnet-sonarscanner@v5.3
      with:
        buildCommand: dotnet build .
        projectKey: swoods91_CSDCA1
        projectName: swoods91_CSDCA1
        sonarOrganisation: swoods91
      
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
