name: BPCA_CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./bp-master/BPCalculator
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: bp-master/BPCalculator
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: bp-master/BPCalculator
      
    - name: Run unit tests
      run: dotnet test bp-master/BloodPressureUnitTests\BloodPressureUnitTests.csproj --verbosity normal
      
    - name: Run Specflow tests
      run: dotnet test bp-master/SpecFlowBloodPressureTests\SpecFlowBloodPressureTests.csproj --verbosity normal
      

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.2
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
