name: BPCA_CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./bp-master/BPCalculator
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Run unit tests
      run: dotnet test BloodPressureUnitTests\BloodPressureUnitTests.csproj --verbosity normal -1:trx
    - name: Run Specflow tests
      run: dotnet test SpecFlowBloodPressureTests\SpecFlowBloodPressureTests.csproj --verbosity normal -1:trx
